### ISSUE TITLE
tango groups behaviour with just one failing device

### ISSUE THREAD

**Issue by ZeusMarti** [tango-controls/matlab-binding#1]
Hi all,
The following code was used with two test devices, tgroups-01 generates a random value while tgroups-02 always raises an exception.

> GroupId = tango_group_create('test');
> devs={'test/acc/tgroups-01','test/acc/tgroups-02'};
> tango_group_add(GroupId,devs);
> resp=tango_group_read_attribute(GroupId,'double_scalar');
> disp(resp.has_failed)
> disp(resp.replies(1).value)

In a suse 11.1 machine with:
- matlab R2009a
- tango-binding (bliss 1.3 build in 2016 but no reference on the release)
- pytango 7.2.3
- tango 7.1.0

we obtain:

>       1
>      3.7460 

In a debian 9.7 machine with :

- matlab R2017a
- tango-binding 3.1.0
- pytango 9.2.0
- tango 9.2.5

we obtain:

> 
> Struct contents reference from a non-struct array object.
> 
> Error in test_groups (line 7)
> disp(resp.has_failed) 

Could you reproduce what we consider a wrong behaviour?

On the other side, there seems to be no difference using PyTango in any of the abovementioned software versions.

> import tango
> group = tango.Group('test')
> group.add("test/acc/tgroups-01")
> group.add("test/acc/tgroups-02")
> answer = group.read_attribute('double_scalar')
> answer.has_failed()
True
> [x.has_failed() for x in answer]
[False, True]
> [x.get_data().value for x in answer]
[2.7986064516144236, None]

(the only difference in Tango 7 is the import PyTango and also the random value received from the attribute).

Best regards,
Zeus

**Comment by nleclercq** [comment]
@ZeusMarti sorry for the delay. Will try to reproduce the problem as soon as I have access to a Matlab session and time to devote to the problem.  Unless you already patched the code and have and PR to submit.
